[variables]
NIXPACKS_NODE_VERSION = "24"

[phases.setup]
nixPkgs = ["nodejs", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm build:platform"]

[start]
cmd = "pnpm start:platform:deploy"
